name: Build and Deploy
on: [push] // 推送代码触发脚本
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN  }} // github Token
        TARGET_REPO: keyanMalfoy/keyanMalfoy.github.io  // 仓库

        TARGET_BRANCH: prod    // build 之后推到的分支名
        BUILD_SCRIPT: npm && npm run build
        BUILD_DIR: src/.vuepress/dist/     //build 之后的目录
        CNAME:  https://keyanMalfoy.github.io/
